/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:25281dc8-c23d-4494-a888-a3776b7d846f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3m1t0gSqG",
    "aws_user_pools_web_client_id": "294sdanamg8m33bve7imec06v",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "pet79231ba8a1af470587d976185d0ef056160845-phil",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
